#pragma once

#define MAJOR_VERSION 0
#define MINOR_VERSION 1

typedef enum {
    EVENT_UNUSED_EVENT,
    EVENT_SECOND,
    EVENT_GPIO_TOGGLE,
    EVENT_CAN_TRANSMIT,
    EVENT_CAN_READY,
    EVENT_ADDRESS_UPDATE,
    EVENT_WAKE,

    EVENT_OUTPUT_SET,
    EVENT_OUTPUT_CLEAR,
    EVENT_OUTPUT_TOGGLE
} eEventType;
